config/routes.rb
Rails.application.routes.draw do
  get 'book/index'
  get 'book/show'
  get 'book/edit'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get 'home/about', to: 'homes#about'
  resources :user, only:[:update, :index, :show, :edit]
  resources :book, only:[:index, :show, :edit, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :book, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end
  
  def edit
  end
  
  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/book/_list.html.erb
<div class="col-md-3">
<h2>User info</h2>

<table class="table">
<tbody>
<tr><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></tr>
<tr>
<th>name</th>
<th><%= user.name %></th>
</tr>

<tr>
<th>introduction</th>
<th><%= user.introduction %></th>
</tr>
</tbody>
</table>
<%= link_to edit_user_path(user) do %>
<i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
<% end %>

<%= form_with model:book, local: true do |f| %>
<% if book.errors.any? %>
  <h3><%= book.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2 class="mt-3">New book</h2>
<h5>Title</h5>
<%= f.text_field :title %>
<h5>Opinion</h5>
<%= f.text_area :body %>
<br>
<input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
<% end %>
</div>

app/views/book/edit.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>

 <% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model:@book, local: true do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<br>
<input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">

<p>
<%= link_to "Show", book_path(@book) %>
| <%= link_to "Back", books_path %>
</p>

<% end %>
</div>
</div>
</div>

app/views/book/index.html.erb
<div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>

      </tr>
  </tbody>
</table>
    </div>

app/views/book/show.html.erb
<div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody><tr>
        </tr>
      </tbody></table>
    </div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="navbar-nav ml-auto">
        <!--  <li><a class="fas fa-home nav-link text-light" href="/">Home</a></li>-->
        <!--  <li><a class="fas fa-link nav-link text-light" href="/home/about">Users</a></li>-->
        <!--  <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up">Books</a></li>-->
        <!--<li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in">logout</a></li>-->

          <!--<li><link to "Home",root_path   <a class="fas fa-home nav-link text-light" href="/"> Home</a></li>-->

          <!--<li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>-->
          <!--<li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>-->
          <!--<li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>-->
          <% if !user_signed_in? %>
          <li><%= link_to "Home", root_path, class:"fas fa-home nav-link text-light" %></li>
          <li><%= link_to "About", home_about_path, class:"fas fa-link nav-link text-light" %></li>
          <li><%= link_to "sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %></li>
          <li><%= link_to "login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %></li>
          <% else %>
          <li><%= link_to "Home", user_path(current_user), class:"fas fa-home nav-link text-light" %> </li>
          <li><%= link_to "Users", user_index_path, class:"fas fa-users nav-link text-light" %> </li>
          <li><%= link_to "Books", book_index_path, class:"fas fa-book-open nav-link text-light" %> </li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-in-alt nav-link text-light" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<p class="flash"><%= flash[:notice] %></p>
<%= yield %>
  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/user/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>User info</h2>

            <% if @user.errors.any? %>
            <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
            <% end %>

<%= form_with model:@user, local: true do |f| %>
<strong>Name</strong>
<%= f.text_field :name %>
<strong>画像</strong>
  <%= f.attachment_field :profile_image %>
<strong>Introduction</strong>
<%= f.text_area :introduction %>
<br>
<input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
<% end %>
</div>
</div>
</div>

app/views/user/index.html.erb
<div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

    </div>

app/views/user/show.html.erb
<div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <tbody>
  <tr>
</tr>
 </tbody>
</table>
    </div>